# DetectObject.srv

# =========== Request (Controller-> Vision node) ===========
string target_object_id  #찾고자 하는 물체 이름(예: "burger_cheese", "tray_marker_0")

---
# =========== Response (Vision node -> Controller) ===========
bool found  #물체 발견 여부
geometry_msgs/Point position    #물제의 위치(x,y,z) - 로봇 베이스 좌표계 기준
geometry_msgs/Quaternion orientation    #물체의 회전 (x, y, z, w) - 파지 동작을 위해 필요 (Aruco 마커 등)
float32 confidence  #인식 신뢰도 (0.0 ~ 1.0)
string message  디버깅용 메시지 (예: "가려져서 안 보임", "성공")